class ResourceConstants:
    FILE_TYPE_MAPPING = {
        "application/pdf": "PDF",
        "application/msword": "DOC",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "DOCX",
        "application/vnd.ms-excel": "XLS",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "XLSX",
        "application/vnd.ms-powerpoint": "PPT",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation": "PPTX",
        "text/plain": "TXT",
        "text/csv": "CSV",
        "image/jpeg": "JPEG",
        "image/png": "PNG",
        "image/gif": "GIF",
        "image/bmp": "BMP",
        "image/tiff": "TIFF",
        "application/zip": "ZIP",
        "application/x-tar": "TAR",
        "application/x-rar-compressed": "RAR",
        "application/x-7z-compressed": "7Z",
        "video/mp4": "MP4",
        "video/x-msvideo": "AVI",
        "video/x-matroska": "MKV",
        "video/webm": "WEBM",
        "audio/mpeg": "MP3",
        "audio/ogg": "OGG",
        "audio/wav": "WAV",
    }
