# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --nomigrations --cov=. --cov-report=html --reuse-db"
python_files = ["test_*.py"]
markers = [
    "unit: tests that are isolated from the db, external api calls and other mockable internal code.",
]

# ==== Coverage ====
[tool.coverage.run]
include = ["apps/**"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    '*/.venv/*',
    '*/venv/*',
    '*/env/*',
    '*/staticfiles/*',
    '*/config/*',
    '*/__init__.py',
    '*apps.py',
    '*urls.py',
    '*wsgi.py',
    '*asgi.py',
    '*manage.py',
    '*requirements.txt',
]

# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = ["apps", "config"]
skip = [".venv/"]
skip_glob = ["**/migrations/*.py"]


# ==== PyLint ====
[tool.pylint.MASTER]
load-plugins = ["pylint_django", "pylint_celery"]
django-settings-module = "config.settings.development"

[tool.pylint.FORMAT]
max-line-length = 119

[tool.pylint."MESSAGES CONTROL"]
disable = ["missing-docstring", "invalid-name"]
