# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --nomigrations --cov=. --cov-report=html --reuse-db"
python_files = ["test_*.py"]
markers = [
    "unit: tests that are isolated from the db, external api calls and other mockable internal code.",
]

# ==== Coverage ====
[tool.coverage.run]
include = ["apps/**"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    '*/.venv/*',
    '*/venv/*',
    '*/env/*',
    '*/staticfiles/*',
    '*/config/*',
    '*/__init__.py',
    '*apps.py',
    '*urls.py',
    '*wsgi.py',
    '*asgi.py',
    '*manage.py',
    '*requirements.txt',
]


[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "migrations"
]

show-fixes = true
target-version = "py311"

line-length = 119
indent-width = 4

[tool.ruff.lint]
extend-select = [
    "E",
    "I",
    "PL",
    "RUF",
]
ignore = ["RUF012"]

fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
skip-magic-trailing-comma = false

line-ending = "auto"