{
    "user": {"username": "jane_doe", "first_name": "Jane", "middle_name": "Bob", "last_name": "Doe"},
    "faculty": "FACULTY OF COMPUTING",
    "department": "INFORMATION SYSTEMS",
    "year_in_school": 2,
    "admission_date": "2023-09-01",
    "graduation_date": "2027-06-01",
},
{
    "user": {"username": "bdu1234556", "first_name": "Jane", "middle_name": "Bob", "last_name": "Doe"},
    "faculty": "FACULTY OF COMPUTING",
    "department": "INFORMATION SYSTEMS",
    "year_in_school": 2,
    "admission_date": "2023-09-01",
    "graduation_date": "2027-06-01",
},
{
    "user": {"username": "bdu1230552", "first_name": "Jane", "middle_name": "Bob", "last_name": "Doe"},
    "faculty": "FACULTY OF COMPUTING",
    "department": "INFORMATION SYSTEMS",
    "year_in_school": 2,
    "admission_date": "2023-09-01",
    "graduation_date": "2027-06-01",
},
{
    "user": {"username": "goodteacher", "first_name": "Jane", "middle_name": "Bob", "last_name": "Doe"},
    "faculty": "FACULTY OF COMPUTING",
    "departments": ["INFORMATION SYSTEMS"],
},
{
    "user": {"username": "admin", "first_name": "Jane", "middle_name": "Bob", "last_name": "Doe"},
    "faculty": "FACULTY OF COMPUTING",
},
