# Generated by Django 4.2 on 2024-05-30 18:35

import apps.resources.models.resource_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("vote_count", models.IntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("score", models.IntegerField(default=0, help_text="The score of the post. upvotes - downvotes.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
            },
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("file", models.FileField(upload_to=apps.resources.models.resource_models.resource_directory_path)),
                ("file_name", models.CharField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_size", models.FloatField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="resources.resource"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="resources", to="resources.resourcecategory"),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="resources", to="forum.tag"),
        ),
        migrations.AddField(
            model_name="resource",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="resources", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
