# Generated by Django 4.2 on 2024-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcecategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
