# Generated by Django 4.2 on 2024-05-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0006_answer_is_active_bookmark_is_active_and_more"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="resources", to="resources.resourcecategory"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="resources", to="forum.tag"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="resources", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
