# Generated by Django 4.2 on 2024-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_resourcecategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="file_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
