# Generated by Django 4.2 on 2024-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_resource_categories_alter_resource_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
