# Generated by Django 4.2.11 on 2024-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                choices=[
                    ("COMPUTER SCIENCE", "Computer Science"),
                    ("INFORMATION TECHNOLOGY", "Information Technology"),
                    ("SOFTWARE ENGINEERING", "Software Engineering"),
                    ("INFORMATION SYSTEMS", "Information Systems"),
                    ("CYBER SECURITY", "Cyber Security"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
