# Generated by Django 4.2 on 2024-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_populate_faculty_and_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facultyadmin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
