# Generated by Django 4.2.11 on 2024-04-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_populate_faculty_and_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
    ]
