# Generated by Django 4.2 on 2024-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("M", "M"), ("F", "F")], default="M", max_length=1),
            preserve_default=False,
        ),
    ]
