# Generated by Django 4.2 on 2024-05-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="points",
        ),
    ]
