# Generated by Django 4.2.11 on 2024-04-06 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_role", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
