# Generated by Django 4.2 on 2024-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_add_initial_roles_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
