# Generated by Django 4.2 on 2024-04-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_answer_is_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
