# Generated by Django 4.2 on 2024-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_viewtracker_viewtracker_view__1"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="viewtracker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
