# Generated by Django 4.2 on 2024-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_answer_is_active_bookmark_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="score",
            field=models.IntegerField(default=0, help_text="The score of the post. upvotes - downvotes."),
        ),
    ]
